services:
  web-interface:
    build: ./web-interface
    restart: always
    ports:
      - "4200:4200"
    networks:
      - librarian-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      args:
        - VERSION=${BACKEND_VERSION:-1.0.0}
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      librarian-network:
    depends_on:
      - database

  database:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    networks:
      librarian-network:
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d


volumes:
  database_data:


networks:
  librarian-network:
    driver: bridge
