name: librarian-dev


services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "4200:4200"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
    networks:
      - librarian-dev-network
    depends_on:
      - gateway-dev

  gateway-dev:
    build:
      context: ./gateway
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "443:443"
    develop:
      watch:
        - action: sync+restart
          path: ./gateway/src
          target: /app
    networks:
      - librarian-dev-network


networks:
  librarian-dev-network:
    driver: bridge
