version: '3.8'


services:
  web-interface:
    build: ./web-interface
    restart: always
    ports:
      - "4200:4200"
    networks:
      - librarian-network
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/librarian
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    networks:
      librarian-network:
    depends_on:
      - database
      

  database:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=librarian
    ports:
      - "5432:5432"
    networks:
      librarian-network:
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d


volumes:
  database_data:


networks:
  librarian-network:
    driver: bridge
