name: librarian


services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - librarian-network
    depends_on:
      - gateway

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: always
    ports:
      - "443:443"
    environment:
      - SERVER_SSL_KEY_STORE=/run/secrets/gateway_keystore
      - SERVER_SSL_KEY_STORE_PASSWORD=${GATEWAY_KEYSTORE_PASSWORD}
      - FRONTEND_ORIGIN=http://localhost:8080
    secrets:
      - gateway_keystore
    networks:
      - librarian-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      args:
        - VERSION=${BACKEND_VERSION:-1.0.0}
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8081:8081"
    networks:
      librarian-network:
    depends_on:
      - database

  database:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    networks:
      librarian-network:
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./backend/sql/create:/docker-entrypoint-initdb.d


secrets:
  gateway_keystore:
    file: ./gateway/secrets/gateway-keystore.p12


volumes:
  database_data:


networks:
  librarian-network:
    driver: bridge
