// --------------- AUTHORS ---------------

### Create an author

PUT http://localhost:8081/api/authors/bcaafcc2-ba5c-45f0-8a72-296072a2967f
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Smith",
  "description": "Test description"
}


### Update an author

PATCH http://localhost:8081/api/authors/bcaafcc2-ba5c-45f0-8a72-296072a2967f
Content-Type: application/json

{
  "firstName": "Bob"
}


### Get all authors

GET http://localhost:8081/api/authors


### Get a specific author

GET http://localhost:8081/api/authors/bcaafcc2-ba5c-45f0-8a72-296072a2967f


### Get all books by author

GET http://localhost:8081/api/authors/bcaafcc2-ba5c-45f0-8a72-296072a2967f/books


// --------------- PUBLISHERS ---------------

### Create a publisher

PUT http://localhost:8081/api/publishers/4af1dede-c955-48d4-a23e-5e84d204bc9a
Content-Type: application/json

{
  "name": "Test publisher",
  "websiteUrl": "http://localhost/",
  "description": "Publisher created for testing"
}


### Update a publisher

PATCH http://localhost:8081/api/publishers/4af1dede-c955-48d4-a23e-5e84d204bc9a
Content-Type: application/json

{
  "description": "Updated description"
}


### Get all publishers

GET http://localhost:8081/api/publishers


### Get a specific publisher

GET http://localhost:8081/api/publishers/4af1dede-c955-48d4-a23e-5e84d204bc9a


### Get books by publisher

GET http://localhost:8081/api/publishers/4af1dede-c955-48d4-a23e-5e84d204bc9a/books



// --------------- BOOKS ---------------

### Create a book

PUT http://localhost:8081/api/books/d33e6abf-7b13-42c2-9816-f4c56c462abf
Content-Type: application/json

{
  "isbn": "978-2-8785-1039-3",
  "title": "Test book",
  "description": "Book created for testing purposes.",
  "author": "bcaafcc2-ba5c-45f0-8a72-296072a2967f",
  "publisher": "4af1dede-c955-48d4-a23e-5e84d204bc9a"
}


### Update a book

PATCH http://localhost:8081/api/books/d33e6abf-7b13-42c2-9816-f4c56c462abf
Content-Type: application/json

{
  "title": "Test book 2"
}


### Get all books

GET http://localhost:8081/api/books


### Get a specific book

GET http://localhost:8081/api/books/d33e6abf-7b13-42c2-9816-f4c56c462abf



// --------------- LIBRARIES ---------------

### Create a library

PUT http://localhost:8081/api/libraries/f9d6f84e-3c81-4404-8e65-7d03c445a7b4
Content-Type: application/json

{
  "name": "Main Library",
  "address": "test street 1, Test",
  "description": "The first library, used for testing."
}


### Update a library

PATCH http://localhost:8081/api/libraries/f9d6f84e-3c81-4404-8e65-7d03c445a7b4
Content-Type: application/json

{
  "address": "test street  2, Test"
}


### Get all libraries

GET http://localhost:8081/api/libraries


### Get a specific library

GET http://localhost:8081/api/libraries/f9d6f84e-3c81-4404-8e65-7d03c445a7b4


### Delete a library

DELETE http://localhost:8081/api/libraries/f9d6f84e-3c81-4404-8e65-7d03c445a7b4


### Get a specfic book from library

GET http://localhost:8081/api/libraries/f9d6f84e-3c81-4404-8e65-7d03c445a7b4/books/d33e6abf-7b13-42c2-9816-f4c56c462abf


### Get all books from library

GET http://localhost:8081/api/libraries/f9d6f84e-3c81-4404-8e65-7d03c445a7b4/books


### Add book to library

PUT http://localhost:8081/api/libraries/f9d6f84e-3c81-4404-8e65-7d03c445a7b4/books/d33e6abf-7b13-42c2-9816-f4c56c462abf
Content-Type: application/json

{
  "numberOfCopies": 3
}


### Delete a book from library

DELETE http://localhost:8081/api/libraries/f9d6f84e-3c81-4404-8e65-7d03c445a7b4/books/d33e6abf-7b13-42c2-9816-f4c56c462abf
