// --------------- AUTHORS ---------------

### Create an author

PUT http://localhost:8080/api/authors/bcaafcc2-ba5c-45f0-8a72-296072a2967f
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Smith"
}


### Update an author

PATCH http://localhost:8080/api/authors/bcaafcc2-ba5c-45f0-8a72-296072a2967f
Content-Type: application/json

{
  "firstName": "Bob"
}


### Get all authors

GET http://localhost:8080/api/authors


### Get a specific author

GET http://localhost:8080/api/authors/bcaafcc2-ba5c-45f0-8a72-296072a2967f



// --------------- PUBLISHERS ---------------

### Create a publisher

PUT http://localhost:8080/api/publishers/4af1dede-c955-48d4-a23e-5e84d204bc9a
Content-Type: application/json

{
  "websiteUrl": "http://localhost/",
  "description": "Publisher created for testing"
}


### Update a publisher

PATCH http://localhost:8080/api/publishers/4af1dede-c955-48d4-a23e-5e84d204bc9a
Content-Type: application/json

{
  "description": "Updated description"
}


### Get all publishers

GET http://localhost:8080/api/publishers


### Get a specific publisher

GET http://localhost:8080/api/publishers/4af1dede-c955-48d4-a23e-5e84d204bc9a



// --------------- BOOKS ---------------

### Create a book

PUT http://localhost:8080/api/books/d33e6abf-7b13-42c2-9816-f4c56c462abf
Content-Type: application/json

{
  "isbn": "978-2-8785-1039-3",
  "title": "Test book",
  "author": "bcaafcc2-ba5c-45f0-8a72-296072a2967f",
  "publisher": "4af1dede-c955-48d4-a23e-5e84d204bc9a"
}


### Update a book

PATCH http://localhost:8080/api/books/d33e6abf-7b13-42c2-9816-f4c56c462abf
Content-Type: application/json

{
  "title": "Test book 2"
}


### Get all books

GET http://localhost:8080/api/books


### Get a specific book

GET http://localhost:8080/api/books/d33e6abf-7b13-42c2-9816-f4c56c462abf
