spring:
  application:
    name: "librarian-gateway"
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: backend
              uri: http://backend:8081
              predicates:
                - Path=/api/**

server:
  port: 443
