spring:
  application:
    name: "librarian-gateway"
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: backend
              uri: http://backend:8081
              predicates:
                - Path=/api/**

server:
  port: 443
  ssl:
    enabled: true
    key-alias: scg
    key-store: ${SERVER_SSL_KEY_STORE}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD}
    key-store-type: PKCS12
