spring:
  application:
    name: "librarian-backend"
  jpa:
    open-in-view: false
server:
  servlet:
    context-path: /api
springdoc:
  api-docs:
    path: /docs/download
  swagger-ui:
    path: /docs
