spring:
  application:
    name: "librarian-backend"
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /api
springdoc:
  api-docs:
    path: /docs/download
  swagger-ui:
    path: /docs
